  {
    "id": 291,
    "code": "X0058",
    "xmlPath": "HPXML.Building.BuildingDetails.Appliances.ClothesDryer.extension.VentedFlowRate",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 61,
    "stdev": 226804
  },
  {
    "id": 581,
    "code": "X7674",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.WaterHeating.WaterHeatingSystem[WaterHeater1].TankVolume",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 153,
    "stdev": 140173
  },
  {
    "id": 315,
    "code": "X0192",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.SetupTempCoolingSeason",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 166,
    "stdev": 123664
  },
  {
    "id": 314,
    "code": "X0189",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.SetbackTempHeatingSeason",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 190,
    "stdev": 96363
  },
  {
    "id": 354,
    "code": "X1687",
    "xmlPath": "HPXML.Building.BuildingDetails.Enclosure.FrameFloors.FrameFloor[FloorBelowAttic1].Insulation.AssemblyEffectiveRValue",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 215,
    "stdev": 73874
  },
  {
    "id": 316,
    "code": "X0193",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.TotalSetbackHoursperWeekHeating",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 216,
    "stdev": 73612
  },
  {
    "id": 317,
    "code": "X0194",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.TotalSetupHoursperWeekCooling",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 232,
    "stdev": 62995
  },
  {
    "id": 318,
    "code": "X0195",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.extension.SetbackStartHourHeating",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 250,
    "stdev": 34179
  },
  {
    "id": 507,
    "code": "X5241",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].HeatPump[ASHP1].AnnualCoolingEfficiency.Value",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 253,
    "stdev": 24837
  },
  {
    "id": 425,
    "code": "X3807",
    "xmlPath": "HPXML.Building.BuildingDetails.Enclosure.Walls.Wall[WallExposed1].Insulation.AssemblyEffectiveRValue",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 254,
    "stdev": 24768
  },
  {
    "id": 311,
    "code": "X0177",
    "xmlPath": "HPXML.Building.BuildingDetails.Enclosure.AirInfiltration.AirInfiltrationMeasurement.BuildingAirLeakage.AirLeakage",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 255,
    "stdev": 23833
  },
  {
    "id": 379,
    "code": "X2677",
    "xmlPath": "HPXML.Building.BuildingDetails.Enclosure.RimJoists.RimJoist[RimJoistStory2Exposed].Insulation.AssemblyEffectiveRValue",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 256,
    "stdev": 23564
  },
  {
    "id": 520,
    "code": "X5727",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].HeatPump[MiniSplitHP1].AnnualCoolingEfficiency.Value",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 257,
    "stdev": 23564
  },
  {
    "id": 509,
    "code": "X5277",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].HeatPump[ASHP1].AnnualHeatingEfficiency.Value",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 275,
    "stdev": 19774
  },
  {
    "id": 494,
    "code": "X4605",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].CoolingSystem[CentralAirConditioner1].AnnualCoolingEfficiency.Value",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 279,
    "stdev": 19016
  },
  {
    "id": 522,
    "code": "X5763",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].HeatPump[MiniSplitHP1].AnnualHeatingEfficiency.Value",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 283,
    "stdev": 15317
  },
  {
    "id": 319,
    "code": "X0196",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.extension.SetupStartHourCooling",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 285,
    "stdev": 12954
  },
  {
    "id": 288,
    "code": "X0000",
    "xmlPath": "HPXML.Building.BuildingDetails.Appliances.ClothesDryer.CombinedEnergyFactor",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 292,
    "stdev": 8342
  },
  {
    "id": 576,
    "code": "X7509",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.WaterHeating.WaterHeatingSystem[WaterHeater1].EnergyFactor",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 295,
    "stdev": 5557
  },
  {
    "id": 380,
    "code": "X2678",
    "xmlPath": "HPXML.Building.BuildingDetails.Enclosure.RimJoists.RimJoist[RimJoistStory3Exposed].Insulation.AssemblyEffectiveRValue",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 297,
    "stdev": 5392
  },
    {
    "id": 351,
    "code": "X1507",
    "xmlPath": "HPXML.Building.BuildingDetails.Enclosure.FrameFloors.FrameFloor[FloorAboveVentedCrawl1].Insulation.AssemblyEffectiveRValue",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 303,
    "stdev": 4040
  },
  {
    "id": 407,
    "code": "X3432",
    "xmlPath": "HPXML.Building.BuildingDetails.Enclosure.Slabs.Slab[SlabOfBasementConditioned1].extension.CarpetRValue",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 307,
    "stdev": 2408
  },
  {
    "id": 525,
    "code": "X5805",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].HeatPump[MiniSplitHP1].BackupSystemFuel",
    "label": null,
    "categoricalValue": "electricity",
    "isActionable": true,
    "dataType": null,
    "importanceRank": 309,
    "stdev": 1601
  },
    {
    "id": 476,
    "code": "X4389",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACDistribution[HVACDistributionAir1].DistributionSystemType.AirDistribution.AirDistributionType",
    "label": null,
    "categoricalValue": "regular velocity",
    "isActionable": true,
    "dataType": null,
    "importanceRank": 314,
    "stdev": 1601
  },
  {
    "id": 477,
    "code": "X4391",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACDistribution[HVACDistributionAir1].DistributionSystemType.AirDistribution.AirDistributionType",
    "label": null,
    "categoricalValue": "gravity",
    "isActionable": true,
    "dataType": null,
    "importanceRank": 314,
    "stdev": 1601
  },
  {
    "id": 295,
    "code": "X0094",
    "xmlPath": "HPXML.Building.BuildingDetails.Appliances.CookingRange.FuelType",
    "label": null,
    "categoricalValue": "electricity",
    "isActionable": true,
    "dataType": null,
    "importanceRank": 315,
    "stdev": 1601
  },
  {
    "id": 296,
    "code": "X0096",
    "xmlPath": "HPXML.Building.BuildingDetails.Appliances.CookingRange.FuelType",
    "label": null,
    "categoricalValue": "natural gas",
    "isActionable": true,
    "dataType": null,
    "importanceRank": 315,
    "stdev": 1601
  },
  {
    "id": 297,
    "code": "X0107",
    "xmlPath": "HPXML.Building.BuildingDetails.Appliances.CookingRange.FuelType",
    "label": null,
    "categoricalValue": "propane",
    "isActionable": true,
    "dataType": null,
    "importanceRank": 315,
    "stdev": 1601
  },
  {
    "id": 524,
    "code": "X5799",
    "xmlPath": "HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].HeatPump[MiniSplitHP1].BackupAnnualHeatingEfficiency.Value",
    "label": null,
    "categoricalValue": null,
    "isActionable": true,
    "dataType": "__double__",
    "importanceRank": 316,
    "stdev": 1601
  },