export const xmlPathLabels = {
  'HPXML.Building.BuildingDetails.BuildingSummary.BuildingConstruction.ConditionedFloorArea': 'Conditioned Floor Area',
  'HPXML.Building.BuildingDetails.Enclosure.Walls.Wall[WallExposed1].Area': 'Exposed Wall Area',
  'HPXML.Building.BuildingDetails.Enclosure.RimJoists.RimJoist[RimJoistCrawlspaceVentedExposed1].Area': 'Rim Joist Crawl Exposed Area',
  'HPXML.Building.BuildingDetails.Enclosure.RimJoists.RimJoist[RimJoistStory2Exposed].Area': 'Rim Joist 2nd Story Exposed Area',
  'HPXML.Building.BuildingDetails.Appliances.ClothesDryer.extension.VentedFlowRate': 'Dryer Vented Flow Rate',
  'HPXML.Building.BuildingDetails.Enclosure.Windows.Window[WindowSouth1].Area': 'Window South Area',
  'HPXML.Building.BuildingDetails.Enclosure.Windows.Window[WindowNorth1].Area': 'Window North Area',
  'HPXML.Building.BuildingDetails.Enclosure.Windows.Window[WindowEast1].Area': 'Window East Area',
  'HPXML.Building.BuildingDetails.Enclosure.Windows.Window[WindowWest1].Area': 'Window West Area',
  'HPXML.Building.BuildingDetails.Systems.WaterHeating.WaterHeatingSystem[WaterHeater1].TankVolume': 'Water Heater Tank Volume',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.SetupTempCoolingSeason': 'Setup Temp Cooling Season',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.SetbackTempHeatingSeason': 'Setback Temp Heating Season',
  'HPXML.Building.BuildingDetails.Enclosure.FrameFloors.FrameFloor[FloorBelowAttic1].Insulation.AssemblyEffectiveRValue': 'Attic Insulation',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.TotalSetbackHoursperWeekHeating': 'Total Setback Hours/Week Heating',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.TotalSetupHoursperWeekCooling': 'Total Setup Hours/Week Cooling',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.extension.SetbackStartHourHeating': 'Setback Start Hour Heating',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].HeatPump[ASHP1].AnnualCoolingEfficiency.Value': 'Heat Pump Cooling Efficiency',
  'HPXML.Building.BuildingDetails.Enclosure.Walls.Wall[WallExposed1].Insulation.AssemblyEffectiveRValue': 'Wall Exposed Insulation',
  'HPXML.Building.BuildingDetails.Enclosure.AirInfiltration.AirInfiltrationMeasurement.BuildingAirLeakage.AirLeakage': 'Air Leakage',
  'HPXML.Building.BuildingDetails.Enclosure.RimJoists.RimJoist[RimJoistStory2Exposed].Insulation.AssemblyEffectiveRValue': 'Rim Joist 2nd Story Insulation',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACPlant[HVACPlant1].HeatPump[ASHP1].AnnualHeatingEfficiency.Value': 'Heat Pump Heating Efficiency',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACControl.extension.SetupStartHourCooling': 'Setup Start Hour Cooling',
  'HPXML.Building.BuildingDetails.Appliances.ClothesDryer.CombinedEnergyFactor': 'Dryer Energy Factor',
  'HPXML.Building.BuildingDetails.Systems.WaterHeating.WaterHeatingSystem[WaterHeater1].EnergyFactor': 'Water Heater Energy Factor',
  'HPXML.Building.BuildingDetails.Enclosure.FrameFloors.FrameFloor[FloorAboveVentedCrawl1].Insulation.AssemblyEffectiveRValue': 'Crawl Insulation',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACDistribution[HVACDistributionAir1].DistributionSystemType.AirDistribution.NumberofReturnRegisters': 'AirDistribution Return Registers',
  'HPXML.Building.BuildingDetails.Enclosure.Slabs.Slab[SlabOfBasementConditioned1].extension.CarpetRValue': 'Basement Carpet RValue',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACDistribution[HVACDistributionAir1].DistributionSystemType.AirDistribution.DuctLeakageMeasurement[HVACDistributionAir1Supply].DuctLeakage.TotalOrToOutside':
    'Duct Supply Leakage',
  'HPXML.Building.BuildingDetails.Systems.HVAC.HVACDistribution[HVACDistributionAir1].DistributionSystemType.AirDistribution.DuctLeakageMeasurement[HVACDistributionAir1Return].DuctLeakage.TotalOrToOutside':
    'Duct Return Leakage',
}
